2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_setup.py:_flush():67] Configure stats pid to 25482
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_setup.py:_flush():67] Loading settings from /home/mallikarjun/.config/wandb/settings
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_setup.py:_flush():67] Loading settings from /home/mallikarjun/da6401_assignment1/wandb/settings
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/mallikarjun/da6401_assignment1/wandb/run-20250302_153327-c970tv0m/logs/debug.log
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/mallikarjun/da6401_assignment1/wandb/run-20250302_153327-c970tv0m/logs/debug-internal.log
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:init():761] calling init triggers
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:init():784] starting backend
2025-03-02 15:33:27,968 INFO    MainThread:25482 [wandb_init.py:init():788] sending inform_init request
2025-03-02 15:33:27,969 INFO    MainThread:25482 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-02 15:33:27,969 INFO    MainThread:25482 [wandb_init.py:init():803] backend started and connected
2025-03-02 15:33:27,970 INFO    MainThread:25482 [wandb_init.py:init():896] updated telemetry
2025-03-02 15:33:27,973 INFO    MainThread:25482 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 15:33:28,429 INFO    MainThread:25482 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 15:33:28,538 INFO    MainThread:25482 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 15:33:28,538 INFO    MainThread:25482 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 15:33:28,538 INFO    MainThread:25482 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 15:33:28,538 INFO    MainThread:25482 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 15:33:28,540 INFO    MainThread:25482 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 15:33:28,582 WARNING MsgRouterThr:25482 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/mallikarjun/da6401_assignment1/da_ass_1/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mallikarjun/da6401_assignment1/da_ass_1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mallikarjun/da6401_assignment1/da_ass_1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mallikarjun/da6401_assignment1/da_ass_1/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/mallikarjun/da6401_assignment1/da_ass_1/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 15:33:28,583 INFO    MsgRouterThr:25482 [mailbox.py:close():115] Closing mailbox, abandoning 3 handles.
